apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: argocd
spec:
  selector:
    app: solar-system
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
